name: Main Actions

on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened ]
  push:
    branches: [ main ]
  create:
    tags:
      - v*

jobs:
  game_actions:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpunit
      - name: Run tests
        run: phpunit tests/GameTest.php
      -   name: PHPUnit tests
          uses: php-actions/phpunit@v3
          with:
            version: '9.6.1'
            php_version: '8.1'
            memory_limit: "1024M"
            configuration: phpunit.xml.dist
      -   name: PHPStan Complete level 6
          uses: php-actions/phpstan@v3
          with:
            memory_limit: '1024M'
            php_version: '8.1'
            path: src
            level: 6
      -   name: PHPStan Domain level 9
          uses: php-actions/phpstan@v3
          with:
            memory_limit: '1024M'
            php_version: '8.1'
            path: src/Domain
            level: 9
      -   name: Deploy to production
          if: github.event_name == 'push' && github.ref == 'refs/heads/main'
          run: echo "Deploying to production"
      -   name: Release new version
          if: startsWith(github.ref, 'refs/tags/v')
          run: echo "Releasing new version"